### ISSUE TITLE
Make sure the number of views is formatted to match the site language

### ISSUE THREAD

**Issue by jeherve** [jeherve/jp-post-views#1]
Basically another pass at https://github.com/jeherve/jp-post-views/commit/919c0e7b39a16d1c25ecb77f34d4618758d8440c

**Comment by lschuyler** [comment]
Arabic requested in 3044275-t

**Comment by jeherve** [comment]
Also reported here:
https://wordpress.org/support/topic/suggested-improvement-to-all-time-site-stats-widget/

**Comment by jeherve** [comment]
It would be nice to round bigger numbers (1000 becomes 1k) as well:
https://wordpress.org/support/topic/how-to-replace-1000-views-with-k/
https://stackoverflow.com/questions/8549463/show-1k-instead-of-1-000

**Comment by jeherve** [comment]
Also here:
https://wordpress.org/support/topic/how-to-insert-commas-between-large-numbers/
