### ISSUE TITLE
Jetpack payant et compteur de vues...

### ISSUE THREAD

**Issue by grapheine** [jeherve/jp-post-views#13]
Bonjour, 

depuis le passage aux statistiques payantes de jetpack, j'ai l'impression que votre pluggin ne fonctionne plus ?

**Comment by jeherve** [comment]
L'extension fonctionne toujours, tant que vous avez accès à vos statistiques. Si l'extension Jetpack vous demande de passer à un plan payant pour accéder à vos statistiques, mon extension aussi ne fonctionnera que si vous avez accès à vos stats.
