### ISSUE TITLE
How to avoid caching of post counts

### ISSUE THREAD

**Issue by kerneltalks** [jeherve/jp-post-views#6]
Great plugin ! 
I installed it and observed post counts are cached since I use W3 total cache plugin on my WP setup. Is there any way out to omit only this plugin or post counters from caching?

**Comment by jeherve** [comment]
Caching is necessary and is done on the plugin's end, even when you don't use a caching plugin. This avoids you from making too many repeated API requests to get the stats from the WordPress.com REST API. If you were to make too many requests you would then be rate limited.

No worries though, you'll see the post stats being refreshed after a little while.

**Comment by kerneltalks** [comment]
" If you were to make too many requests you would then be rate limited." Make sense !!
Thank your for explanation!
